spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imovie
    username: root
    password: lovecan148
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: off